---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cruise-control
  namespace: cruise-control
  labels:
    app: cruise-control
    k2.segment.com/app: cruise-control
    k2.segment.com/argocd: "true"
    k2.segment.com/build: 9a038a0
    k2.segment.com/deploy: 67ce12f920623b
    k2.segment.com/repo: cruise-control
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
    version: 9a038a0-67ce12f920623b
  annotations:
    k2.segment.com/context: '{"appConfigMismatch":false,"appConfigSource":"file://.k2/cc-stage-usw2-dp-sandbox.yaml","appName":"cruise-control","argoCDDeploy":true,"argoCDTestDeploy":false,"buildTag":"9a038a0","deployID":"67ce12f920623b","deployTime":"2022-10-26T06:30:40.704807Z","fullDiffs":false,"host":"C02GK492MD6M","image":null,"k2Root":"/Users/ssingudasu/.kube/k2","k2Version":"0.10.0","repoBranch":"25oct2022-01","repoName":"cruise-control","repoSHA":"0495413d37f4f0ef6b8a6e7215ce8eb70558d60e","skipChecks":true,"skipChecksReason":"","targetCluster":"stage:us-west-2:dp-sandbox","targetName":"cc-stage-usw2-dp-sandbox","user":"ssingudasu","workingDir":"/Users/ssingudasu/Desktop/twilio/projects/cruise-control","shardDeployment":false}'
spec:
  strategy:
    {}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cruise-control
  template:
    metadata:
      labels:
        app: cruise-control
        k2.segment.com/app: cruise-control
        k2.segment.com/argocd: "true"
        k2.segment.com/build: 9a038a0
        k2.segment.com/deploy: 67ce12f920623b
        k2.segment.com/repo: cruise-control
        k2.segment.com/skipped-checks: "true"
        segment.com/managed-by: k2
        version: 9a038a0-67ce12f920623b
      annotations:
        k2.segment.com/context: '{"appConfigMismatch":false,"appConfigSource":"file://.k2/cc-stage-usw2-dp-sandbox.yaml","appName":"cruise-control","argoCDDeploy":true,"argoCDTestDeploy":false,"buildTag":"9a038a0","deployID":"67ce12f920623b","deployTime":"2022-10-26T06:30:40.704807Z","fullDiffs":false,"host":"C02GK492MD6M","image":null,"k2Root":"/Users/ssingudasu/.kube/k2","k2Version":"0.10.0","repoBranch":"25oct2022-01","repoName":"cruise-control","repoSHA":"0495413d37f4f0ef6b8a6e7215ce8eb70558d60e","skipChecks":true,"skipChecksReason":"","targetCluster":"stage:us-west-2:dp-sandbox","targetName":"cc-stage-usw2-dp-sandbox","user":"ssingudasu","workingDir":"/Users/ssingudasu/Desktop/twilio/projects/cruise-control","shardDeployment":false}'
      name: cruise-control
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 169.254.20.10
        searches:
        - cruise-control.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        - us-west-2.compute.internal
        options:
        - name: ndot
          value: '2'
      serviceAccountName: cruise-control
      nodeSelector:
        segment.com/pool: main
      containers:
      - command:
        - /usr/local/cruise-control/kafka-cruise-control-start.sh
        - /usr/local/cruise-control/config/cruisecontrol.properties
        env:
        - name: GOMAXPROCS
          value: "1"
        - name: K8S_CONTAINER_NAME
          value: cruise-control
        - name: K8S_DEPLOYMENT
          value: cruise-control
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SEGMENT_CELL
          value: core
        image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/cruise-control:v2.5.42
        name: cruise-control
        resources:
          limits:
            cpu: 500m
            memory: 512M
        volumeMounts:
        - mountPath: /usr/local/cruise-control/config/cruisecontrol.properties
          name: cruise-control-properties
          subPath: cruisecontrol.properties
        - mountPath: /usr/local/cruise-control/config/capacityCores.json
          name: cruise-control-capacitycores
          subPath: capacityCores.json
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: cruise-control
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
        - configMap:
            name: cruise-control-properties
          name: cruise-control-properties
        - configMap:
            name: cruise-control-capacitycores
          name: cruise-control-capacitycores
        - hostPath:
            path: /var/spool/ctlstore
          name: ctlstore