---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cruise-control
  namespace: cruise-control
  labels:
    app: cruise-control
    k2.segment.com/app: cruise-control
    k2.segment.com/repo: cruise-control
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cruise-control
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75