---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cruise-control
    k2.segment.com/app: cruise-control
    k2.segment.com/repo: cruise-control
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
  name: cruise-control
  namespace: cruise-control
spec:
  clusterIP: None
  ports:
  selector:
    app: cruise-control

